### ISSUE TITLE
Can't find the docs for WinUI 3 version of BackdropMaterial.ApplyToRootOrPageBackground API

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winui-api#121]
I know everything was just restructured, but it used to be that there was a link to just switch between the two versions of the API docs pages.

It just dumps me to the landing page now for all of the WinAppSDK, and I can't search/find the equivalent API for WinUI 3 now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4bbe2c6-226c-18cb-0ebd-8b020b0938b7
* Version Independent ID: e8fbaca8-a741-1dab-b800-ca413e7c3501
* Content: [BackdropMaterial.ApplyToRootOrPageBackground Attached Property (Microsoft.UI.Xaml.Controls) - WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.backdropmaterial.applytorootorpagebackground?view=winui-2.7)
* Content Source: [winui-api-build/xml/Microsoft.UI.Xaml.Controls/BackdropMaterial.xml](https://github.com/MicrosoftDocs/winui-api/blob/docs/winui-api-build/xml/Microsoft.UI.Xaml.Controls/BackdropMaterial.xml)
* Product: **reunion**
* Technology: **winui-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by michael-hawker** [comment]
Related to #119

**Comment by jwmsft** [comment]
@michael-hawker, the BackdropMaterial class is WinUI2/UWP only. There is no WinUI 3 version. Doc updates for Mica in WinUI 3 are nearly ready, but for now the best place to see how to use it is to look at the example in the WinUI 3 Gallery app.

@Karl-Bridge-Microsoft, assigned to you for the general cross-linking feedback. This class shouldn't have a link to the WinUI 3 docs.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @michael-hawker - I think Jim has answered your question here. There were a lot of moving parts to this restructuring and because of much duplication of APIs between UWP, WinUI2, WinUI in the WIndows App SDK, global search and replaces were problematic and had the potential to introduce many more issues that would be difficult to recover cleanly from. I decided to err on the side of caution. Our build tools were also an issue over the last week or so, which slowed things down a bit. Closing this issue and will respond to other open issues related to the restructuring and link breaks.
